services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=uknf_user
      - POSTGRES_PASSWORD=YourStrong@Passw0rd
      - POSTGRES_DB=uknf_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - uknf-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uknf_user -d uknf_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./src/Backend
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=uknf_db;Username=uknf_user;Password=YourStrong@Passw0rd
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - uknf-network

  frontend:
    build:
      context: ./src/Frontend/uknf-portal
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - uknf-network

volumes:
  pgdata:

networks:
  uknf-network:
    driver: bridge
