// This is a sample GitHub Actions workflow for building, pushing, and deploying containers to Azure Web App for Containers
// Copy and adapt as needed

name: Deploy to Azure Web App for Containers

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_WEBAPP_NAME_BACKEND: <your-backend-app>
      AZURE_WEBAPP_NAME_FRONTEND: <your-frontend-app>
      AZURE_CONTAINER_REGISTRY: <your-acr-name>.azurecr.io
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and push backend image
        run: |
          docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}/uknf-backend:${{ env.IMAGE_TAG }} ./backend
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/uknf-backend:${{ env.IMAGE_TAG }}
      - name: Build and push frontend image
        run: |
          docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}/uknf-frontend:${{ env.IMAGE_TAG }} ./frontend
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/uknf-frontend:${{ env.IMAGE_TAG }}
      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_BACKEND }}
          images: ${{ env.AZURE_CONTAINER_REGISTRY }}/uknf-backend:${{ env.IMAGE_TAG }}
      - name: Deploy frontend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_FRONTEND }}
          images: ${{ env.AZURE_CONTAINER_REGISTRY }}/uknf-frontend:${{ env.IMAGE_TAG }}
